# https://vuepress.github.io/zh/guide/deployment.html#github-pages
name: docs

on:
  # 每当 push 到 vuepress 分支时触发部署
  push:
    branches: [vuepress]
  # 手动触发部署
  workflow_dispatch:

jobs:
  docs:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2.3.4
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v2.4.0
        with:
          # 选择要使用的 node 版本
          node-version: '14.17.5'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'

      # 如果缓存没有命中，安装依赖
      - name: Install Dependencies
        run: yarn install

      # 运行 Gitee 构建脚本
      - name: Build Gitee VuePress Site
        run: yarn gitee:build

      # 部署到 Github Pages
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # 部署到 main 分支
          target_branch: main
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 同步到 Gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1.0.1
        with:
          # 源仓库地址
          source-repo: git@github.com:ModyQyW/modyqyw.github.io.git
          # 目标仓库地址
          destination-repo: git@gitee.com:ModyQyW/ModyQyW.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}

      # 部署到 Gitee Pages
      - name: Deploy to Gitee Pages
        uses: yanglbme/gitee-pages-action@v1.3.1
        with:
          # 账号
          gitee-username: ModyQyW
          # 密码
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 仓库
          gitee-repo: ModyQyW/ModyQyW
          # 部署 main 分支
          branch: main

      # 运行 Github 构建脚本
      - name: Build Github VuePress Site
        run: yarn github:build

      # 重新部署到 Github Pages
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.5.0
        with:
          # 部署到 main 分支
          target_branch: main
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
