name: git-pages

on:
  push:
    branches:
      - main
      - release
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  git-pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: pnpm/action-setup@v2
        with:
          version: latest

      - uses: actions/setup-node@v3
        with:
          node-version: lts/*
          cache: pnpm

      - run: pnpm install --no-frozen-lockfile

      - run: pnpm run build
        env:
          ALGOLIA_APP_ID: ${{ secrets.ALGOLIA_APP_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_API_KEY }}
          ALGOLIA_INDEX_NAME: ${{ secrets.ALGOLIA_INDEX_NAME }}

      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: git-pages
          build_dir: docs/.vitepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
