# https://vuepress.github.io/zh/guide/deployment.html#github-pages
name: git-pages

on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  git-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          # “最近更新时间” 等 git 日志相关信息，需要拉取全部提交记录
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.0.1
        with:
          version: 'latest'

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          # 选择要使用的 node 版本
          node-version: '16'
          cache: 'pnpm'

      # 如果缓存没有命中，安装依赖
      - name: Install Dependencies
        run: pnpm install

      # 清理临时文件和缓存
      - name: Clear temp and cache
        run: rm -rf ./docs/.vuepress/.temp ./docs/.vuepress/dist ./node_modules/.vite

      # 运行 Gitee 构建脚本
      - name: Build Gitee Pages
        run: pnpm run build:gitee

      # 部署到 Github Pages
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          target_branch: git-pages
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 同步到 Gitee
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@v1
        with:
          # 源仓库地址
          source-repo: git@github.com:ModyQyW/modyqyw.github.io.git
          # 目标仓库地址
          destination-repo: git@gitee.com:ModyQyW/ModyQyW.git
        env:
          SSH_PRIVATE_KEY: ${{ secrets.RSA_PRIVATE_KEY }}

      # 部署到 Gitee Pages
      - name: Deploy to Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 账号
          gitee-username: ModyQyW
          # 密码
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 仓库
          gitee-repo: ModyQyW/ModyQyW
          # 部署 git-pages 分支
          branch: git-pages

      # 清理临时文件和缓存
      - name: Clear temp and cache
        run: rm -rf ./docs/.vuepress/.temp ./docs/.vuepress/dist ./node_modules/.vite

      # 运行 Github 构建脚本
      - name: Build Github Pages
        run: pnpm run build:github

      # 重新部署到 Github Pages
      # 查看 workflow 的文档来获取更多信息
      # @see https://github.com/crazy-max/ghaction-github-pages
      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2
        with:
          # 部署到 git-pages 分支
          target_branch: git-pages
          # 部署目录为 VuePress 的默认输出目录
          build_dir: docs/.vuepress/dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
